const PRODUCTS_MANAGEMENT_REQUEST = '@productsManagement/PRODUCTS_MANAGEMENT_REQUEST';
const PRODUCTS_MANAGEMENT_SUCCESS = '@productsManagement/PRODUCTS_MANAGEMENT_SUCCESS';
const PRODUCTS_MANAGEMENT_FAILED = '@productsManagement/PRODUCTS_MANAGEMENT_FAILED';

export { PRODUCTS_MANAGEMENT_REQUEST, PRODUCTS_MANAGEMENT_SUCCESS, PRODUCTS_MANAGEMENT_FAILED }